#!/usr/bin/env bash

function clean() {
  case "$1" in

    # `clean apps` | Remove unwanted apps that restore themselves after updates
    "apps")
      echo 'Removing unwanted apps…';
      sudo rm -rf /Applications/Google\ Docs.app
      sudo rm -rf /Applications/Google\ Sheets.app
      sudo rm -rf /Applications/Google\ Slides.app
      rm -rf ~/Google\ Drive
    ;;

    # `clean cache` | Remove cache files
    "cache") echo 'Removing local cache…'; rm -rf .cache ;;

    # `clean clipboard` | Empty clipboard
    "clipboard") echo 'Emptying clipboard…'; pbcopy < /dev/null ;;

    # `clean dsstore` | Remove Finder metadata files under the current directory
    "dsstore") echo 'Removing .DS_Store files…'; find . -type f -name ".DS_Store" -print -delete ;;

    # `clean logs` | Remove Apple's system logs to improve shell startup speed
    "logs") echo 'Removing logs…'; sudo rm -rfv /private/var/log/asl/*.asl ;;

    # `clean ssh` | Dedupe ssh known hosts
    "ssh")
      echo 'Deduping SSH known hosts…'
      if [[ -f "${HOME}/.ssh/known_hosts" ]]; then
        tmp=$(mktemp)
        awk '!seen[$0]++' "${HOME}/.ssh/known_hosts" > "$tmp"
        mv "$tmp" "${HOME}/.ssh/known_hosts"
      fi
    ;;

    # `clean` | Run all the clean commands
    "")
      clean apps
      clean cache
      clean clipboard
      clean dsstore
      clean logs
      clean ssh
    ;;

  esac
}

complete -W "apps cache clipboard dsstore logs ssh" clean

function fix() {
  case "$1" in

    # `fix audio` | When audio isn't working
    "audio") sudo pkill coreaudiod ;;

    # `fix app /Applications/name.app` | When an app tells you "This app is damaged and can't be opened. You should move it to the trash."
    "app") shift 1; xattr -rc "$@" ;;

  esac
}

complete -W "audio app" fix
