#!/usr/bin/env bash

# `download` or `dl`
function download() {
  if [[ -z "$1" ]]; then
    wget
    return
  fi

  if [[ -z "$3" ]]; then params="$1"; else params="$1 $2"; fi
  case "$params" in
    # `download links ./x.txt` | Download a list of links from a file
    "links") shift 1; wget -r --no-remove-listing -i "$1" ;;

    # `download music https://www.youtube.com/watch?v=id` | Download music
    "music") shift 1; yt-dlp --extract-audio --audio-format mp3 "$1" ;;

    # `download video https://www.youtube.com/watch?v=id` | Get mp4 with the best video and audio
    "video") shift 1; yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' "$1" ;;

    # `download video range https://www.youtube.com/watch?v=id 00:15:00 00:45:00`
    "video range") shift 2
      vurl="$1"
      startTime="$2"
      endTime="$3"
      title="${4:-video}"

      if [[ -z "$vurl" || -z "$startTime" || -z "$endTime" ]]; then
        echo "usage: download video range URL START END [TITLE]"
        return 2
      fi

      range=(
        ffmpeg
        -ss "$startTime"
        -to "$endTime"
        -i "$(yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4/best' --get-url "$vurl")"
        -r 30
        -crf 18
        -vcodec libx264
        -acodec aac
        -movflags +faststart
        -n
        "$title.mp4"
      )
      "${range[@]}"
    ;;

    # `download video thumbnail https://www.youtube.com/watch?v=id 00:15:00 00:45:00`
    "video thumbnail") shift 2; yt-dlp --skip-download --write-thumbnail "$1" ;;

    # `download https://google.com`
    *) wget "$@" ;;
  esac
}

alias dl="download"

complete -W "links music video 'video range' 'video thumbnail'" download dl

alias mget="download music"
alias vget="download video"
complete mget vget
