#!/usr/bin/env bash

function image() {
  case "$1" in
    # Image Resize Parameters: size (width in pixels, height is automatic), file, outputdir
    # `image resize 300 "x.jpg" out` | Optimal settings for resizing an image
    "resize") shift 1; mogrify -path $3 -resize $1 -quality 85 -density 72 -strip $2 ;;
  esac
}

function images() {
  case "$1" in
    # Images Resize Parameters: size (width in pixels, height is automatic), outputdir
    # `images resize 300 out` | Resize in batch form
    # crush 300 out
    "resize") shift 1; for f in "$(pwd)/*" ; do image resize $1 "${f}" $2/; done ;;
  esac
}

complete -W "resize" image images
