#!/usr/bin/env bash

function fix() {
  case "$1" in

    # `fix audio` | When audio isn't working
    "audio") sudo pkill coreaudiod ;;

    # `fix app /Applications/name.app` | When an app tells you "This app is damaged and can't be opened. You should move it to the trash."
    "app") xattr -rc $2 ;;

  esac
}

complete -W "audio app" fix

function clean() {
  case "$1" in

    # `clean cache` | Delete cache files
    "cache")
      rm -rf .cache
    ;;

    # `clean clipboard` | Empty clipboard
    "clipboard") pbcopy < /dev/null ;;

    # `clean logs` | Remove Apple's system logs to improve shell startup speed.
    "logs")
      rm -rfv /private/var/log/asl/*.asl
    ;;

    # `clean` | Run all the clean commands
    "")
      echo
      echo ':clean'
      echo
      echo 'Cleaning cache…'
      clean cache
      echo 'Cleaning clipboard…'
      clean clipboard
      echo 'Cleaning logs…'
      clean logs
    ;;

  esac
}

complete -W "cache clipboard logs trash" remove
