#!/usr/bin/env bash

function update() {
  case "$1" in

    # `update apps`
    "apps") echo 'Updating App Store apps…'; mas upgrade ;;

    # `update brew`
    "brew")
      echo 'Updating Homebrew packages…'
      brew upgrade; brew missing; brew cleanup; brew services cleanup
      shell cd ~//apps/
      brew bundle dump --force --describe
      cd -
    ;;

    # `update dock`
    "dock") echo 'Updating Dock…'; ~//dock ;;

    # `update dotfiles`
    "dotfiles") echo 'Updating dotfiles…'; ~//dotfiles/install.sh ;;

    # `update hosts`
    "hosts") echo 'Updating hosts…'; sudo chmod -R o+rwx /etc/hosts; cp ~//hosts /etc/hosts ;;

    # `update links`
    "links")
      echo 'Updating links…'
      # Cloud links :: from computer to Google Drive
      gd="/Volumes/GoogleDrive/My Drive"
      if [ -d "$gd" ]; then
        shell cd "$gd"
        for src in Applications Documents Documents/Projects Games Music Pictures; do
          shell cd "$gd/$src"
          for dir in ./; do
            run=(
              stow --target ~/$src    # target directory
                   --restow           # prunes dead links
                   --verbose 1 "$dir" # options 0-5
                   # --simulate       # use for testing
            )
            "${run[@]}"
          done
        done
      fi

      # NAS links :: from computer to NAS
      nas="/Volumes/Adler"
      if [ -d "$nas" ]; then
        shell cd "$nas"
        for src in Documents/Computer Games Pictures; do
          shell cd "$nas/$src"
          for dir in ./; do
            run=(
              stow --target ~/$src    # target directory
                   --restow           # prunes dead links
                   --verbose 1 "$dir" # options 0-5
                   # --simulate       # use for testing
            )
            "${run[@]}"
          done
        done
      fi

      # Other links
      ln -s /Applications/ ~/Applications/Mac
    ;;

    # `update` | Run all of the updates
    "")
      echo $(text invert)
      echo '                                                                                '
      echo ' :<update>                                                                     '
      echo '                                                                                '
      echo $(text)
      echo 'Requesting root access…'
      root
      shell cd ~
      echo $(text invert)
      echo '                                                                                '
      echo ' :<update links>                                                               '
      echo '                                                                                '
      echo $(text)
      update links
      update dotfiles
      echo $(text invert)
      echo '                                                                                '
      echo ' :<update apps>                                                                '
      echo '                                                                                '
      echo $(text)
      update apps
      update brew
      shell cd ~
      echo $(text invert)
      echo '                                                                                '
      echo ' :<update hosts>                                                               '
      echo '                                                                                '
      echo $(text)
      update hosts
      echo $(text invert)
      echo '                                                                                '
      echo ' :<clean>                                                                      '
      echo '                                                                                '
      echo $(text)
      clean
      # Back up Sublime Text settings'
      cp ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Package\ Control.sublime-settings ~//resources/
      cp ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings ~//resources/
      echo $(text invert)
      echo '                                                                                '
      echo ' :<update macos>                                                               '
      echo '                                                                                '
      echo $(text)
      softwareupdate -i -a
      update dock
      update preferences
    ;;

  esac
}

complete -W "apps brew dock dotfiles hosts links" update
