#!/usr/bin/env bash

function update() {
  case "$1" in

    # `update apps`
    "apps")
      echo 'Updating App Store apps…'
      mas upgrade
      echo 'Updating Homebrew packages…'
      brew upgrade; brew missing; brew cleanup
      shell cd ~//apps/
      brew bundle dump --force --describe
      shell cd -
    ;;

    # `update dock`
    "dock") echo 'Updating Dock…'; ~//dock ;;

    # `update dotfiles`
    "dotfiles") echo 'Updating dotfiles…'; ~//dotfiles/install.sh ;;

    # `update hosts`
    "hosts") echo 'Updating hosts…'; sudo chmod -R o+rwx /etc/hosts; cp ~//hosts /etc/hosts ;;

    # `update links`
    "links")
      echo 'Updating links…'
      ln -sfn /Applications ~/Applications/Mac
    ;;
    # `update preferences`
    "preferences") echo 'Updating Preferences…'; ~//preferences ;;

    # `update` | Run all of the updates
    "")
      echo $(text invert)
      echo '                                                                                '
      echo ' :<update>                                                                     '
      echo '                                                                                '
      echo $(text)
      echo 'Requesting root access…'
      root
      shell cd ~
      echo $(text invert)
      echo '                                                                                '
      echo ' :<update links>                                                               '
      echo '                                                                                '
      echo $(text)
      update dotfiles
      update links
      update hosts
      echo $(text invert)
      echo '                                                                                '
      echo ' :<update apps>                                                                '
      echo '                                                                                '
      echo $(text)
      update apps
      shell cd ~
      echo $(text invert)
      echo '                                                                                '
      echo ' :<clean>                                                                      '
      echo '                                                                                '
      echo $(text)
      clean
      # Back up Sublime Text settings'
      cp ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Package\ Control.sublime-settings ~//resources/
      cp ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings ~//resources/
      echo $(text invert)
      echo '                                                                                '
      echo ' :<update macos>                                                               '
      echo '                                                                                '
      echo $(text)
      softwareupdate -i -a
      update preferences
    ;;

  esac
}

complete -W "apps dock dotfiles hosts links preferences" update
