#!/usr/bin/env bash

function video() {
  case "$1" in

    # Video Encode Parameters: filetype, video codec, audio codec
    # `video encode` | remux all videos in the current directory to mp4
    # `video encode mkv libx265 aac` | encode all videos to mkv with x265 and aac codecs
    "encode") shift 1
      filetype=${1:-mp4}
      video_codec=${2:-copy}
      audio_codec=${3:-copy}
      output=${4:-output}
      mkdir -p $output
      for i in *.mkv *.webm *.flv *.vob *.ogg *.ogv *.drc *gifv *.mng *.avi *.mov *.qt *.wmv *.yuv *.rm *.rmvb *.asf *.amv *.mp4 *.m4v *.mp *.m?v *.svi *.3gp *.flv *.f4v; do
        if [ -f "$i" ]; then
          if [ $1 = true ]
          then
            ffmpeg -i "$i" -map 0 -c:v $video_codec -c:a $audio_codec -y -nostats -loglevel 0 "./$output/${i/${i##*.}/$filetype}"
          else
            ffmpeg -i "$i" -c copy "./$output/${i/${i##*.}/$filetype}"
          fi
        fi
      done
    ;;

    # `video merge ts mkv` | Combine all ts files in the current dir into one mkv file
    "merge") shift 1; ffmpeg -f concat -safe 0 -i <(find "$PWD" -maxdepth 1 -type f \( -iname "*.mkv" -o -iname "*.webm" -o -iname "*.flv" -o -iname "*.vob" -o -iname "*.ogg" -o -iname "*.ogv" -o -iname "*.drc" -o -iname "*.gifv" -o -iname "*.mng" -o -iname "*.avi" -o -iname "*.mov" -o -iname "*.qt" -o -iname "*.wmv" -o -iname "*.yuv" -o -iname "*.rm" -o -iname "*.rmvb" -o -iname "*.asf" -o -iname "*.amv" -o -iname "*.mp4" -o -iname "*.m4v" -o -iname "*.mp" -o -iname "*.m?v" -o -iname "*.svi" -o -iname "*.3gp" -o -iname "*.flv" -o -iname "*.f4v" -o -iname "*.ts" \) -print0 | sort -zV | while IFS= read -r -d '' f; do echo "file '$f'"; done) -c copy "output.${2}" ;;

    # `video scale 1920 1080 input.mp4 output.mp4` | Scale video
    "scale") shift 1; ffmpeg -i $3 -vf scale=$1:$2 $4 ;;

    # `video split 00:10:00 input.mp4` | Split video into multiple parts (00:10:00 means 10 minutes each)
    "split") shift 1; ffmpeg -i $2 -c copy -map 0 -segment_time $1 -f segment -reset_timestamps 1 $2%03d.mp4 ;;

  esac
}

complete -W "encode merge scale split" video
